#!/bin/sh

SOURCE=resume.md
TARGET=resume
CSS=resume.css
OPEN_COMMAND=xdg-open

case "$1" in
  build)
    pandoc --pdf-engine=wkhtmltopdf -t html5 --css "$CSS" -o "$TARGET".pdf "$SOURCE"
    ;;
  docker)
    docker build -t resume .
    docker rm resume-run
    docker create --name resume-run resume:latest
    docker cp resume-run:/usr/src/resume.pdf ./resume.pdf
    ;;
  build-html)
    pandoc --standalone --css "$CSS" --from markdown --to html -o "$TARGET".html "$SOURCE"
    ;;
  open)
    "$OPEN_COMMAND" "$TARGET".pdf &
    ;;
  *)
    echo "Usage: $0 {build|docker|build-html|open}"
    exit 2
esac

exit 0
